### ISSUE TITLE
Strange failure for empty repository

### ISSUE THREAD

**Issue by myselfhimself** [crguezl/gh-submodule-add#6]
If the submodule repository is empty I have this strange error:
```
Skipping to add repo https://github.com/hoeh/KC-features.git because is empty!
assert.js:101
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: [concurrently] no commands provided
    at concurrently (/home/heyho/Productions/KC/KC/node_modules/concurrently/dist/src/concurrently.js:34:22)
    at exports.default (/home/heyho/Productions/KC/KC/node_modules/concurrently/dist/src/index.js:34:44)
    at Object.<anonymous> (/home/heyho/Productions/KC/KC/node_modules/concurrently/dist/bin/concurrently.js:200:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: 0,
  operator: 'notStrictEqual'
}
Error: Command "npx concurrently  -m 1 " failed
assert.js:101
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: [concurrently] no commands provided
    at concurrently (/home/heyho/Productions/KC/KC/node_modules/concurrently/dist/src/concurrently.js:34:22)
    at exports.default (/home/heyho/Productions/KC/KC/node_modules/concurrently/dist/src/index.js:34:44)
    at Object.<anonymous> (/home/heyho/Productions/KC/KC/node_modules/concurrently/dist/bin/concurrently.js:200:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: 0,
  operator: 'notStrictEqual'
}

undefined
Inside urls.forEach
Skipping to add repo https://github.com/hoeh/KC-features.git because is empty!
```

**Comment by crguezl** [comment]
Thanks @myselfhimself , 

I have no time now to fix and maintain this extension. If you know of someone willing to accept the maintenance of this extension I will be grateful.

Thanks

Casiano
